version: 2
updates:
    - package-ecosystem: npm
      directory: /
      versioning-strategy: increase
      schedule:
          interval: monthly
      open-pull-requests-limit: 20
    - package-ecosystem: github-actions
      directory: /
      schedule:
          # Check for updates to GitHub Actions every weekday
          interval: daily
